/*This file is automatically generated from a Keras model*/

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "rnn.h"
#include "rnn_data.h"

#include "rnn_weights.c"

static const DenseLayer input_dense = {
   input_dense_bias,
   input_dense_weights,
   42, 24, ACTIVATION_TANH
};

static const GRULayer vad_gru = {
   vad_gru_bias,
   vad_gru_weights,
   vad_gru_recurrent_weights,
   24, 24, ACTIVATION_RELU
};

static const GRULayer noise_gru = {
   noise_gru_bias,
   noise_gru_weights,
   noise_gru_recurrent_weights,
   90, 48, ACTIVATION_RELU
};

static const GRULayer denoise_gru = {
   denoise_gru_bias,
   denoise_gru_weights,
   denoise_gru_recurrent_weights,
   114, 96, ACTIVATION_RELU
};

static const DenseLayer denoise_output = {
   denoise_output_bias,
   denoise_output_weights,
   96, 22, ACTIVATION_SIGMOID
};

static const DenseLayer vad_output = {
   vad_output_bias,
   vad_output_weights,
   24, 1, ACTIVATION_SIGMOID
};

const struct RNNModel rnnoise_model_orig = {
    24,
    &input_dense,

    24,
    &vad_gru,

    48,
    &noise_gru,

    96,
    &denoise_gru,

    22,
    &denoise_output,

    1,
    &vad_output
};
